version: '3'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    network_mode: "bridge"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_HEAP_MEMORY=5G
      - NEO4J_dbms_memory_pagecache_size=5G
      - NEO4J_dbms_memory_heap_initial__size=5G
    volumes:
      - ../output:/import